=== Tirtan/semestre3/web/xml/partie1/biblio.dtd
<!ELEMENT BIBLIO (LIVRE*) >

	<!ELEMENT LIVRE (TITRE,AUTEUR) >
		<!ELEMENT TITRE  (#PCDATA)     >
		<!ELEMENT AUTEUR (NOM,PRENOM)  >
		
			<!ELEMENT NOM    (#PCDATA) >
			<!ELEMENT PRENOM (#PCDATA) >

=== Tirtan/semestre3/web/xml/partie1/biblio.xml
<?xml version="1.0" ?>

<!DOCTYPE BIBLIO SYSTEM "biblio.dtd">

<BIBLIO>

	<LIVRE>
		<TITRE>L'assommoir</TITRE>
		<AUTEUR>
				<NOM>Zola</NOM>
		<PRENOM>&#201;mile</PRENOM>
		</AUTEUR>
	</LIVRE>
	
	<LIVRE>
		<TITRE>Germinal</TITRE>
		<AUTEUR>
			<NOM>Zola</NOM>
			<PRENOM>&#201;mile</PRENOM>
		</AUTEUR>
	</LIVRE>
	
</BIBLIO>

=== Tirtan/semestre3/web/xml/partie1/biblio_xsslt.xml
<?xml version="1.0" ?>

<!DOCTYPE BIBLIO SYSTEM "biblio.dtd">
<?xml-stylesheet type="text/xsl" href="biblio.xsl"?>

<BIBLIO>

	<LIVRE>
		<TITRE>L'assommoir</TITRE>
		<AUTEUR>
				<NOM>Zola</NOM>
		<PRENOM>&#201;mile</PRENOM>
		</AUTEUR>
	</LIVRE>
	
	<LIVRE>
		<TITRE>Germinal</TITRE>
		<AUTEUR>
			<NOM>Zola</NOM>
			<PRENOM>&#201;mile</PRENOM>
		</AUTEUR>
	</LIVRE>
	
</BIBLIO>
