=== Tirtan/semestre3/web/xml/partie1/kub7.dtd
<!ELEMENT kubenbois (pays*)>
<!ELEMENT pays (agence+)>
<!ATTLIST pays nom CDATA #REQUIRED>
<!ELEMENT agence (responsable)>
<!ATTLIST agence ville CDATA #REQUIRED>
<!ELEMENT responsable (nom,prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>

=== Tirtan/semestre3/web/xml/partie1/07-kubenbois.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!DOCTYPE kubenbois SYSTEM "kub7.dtd">

<kubenbois>

	<!-- - - - - - - - -->
	<!--    France     -->
	<!-- - - - - - - - -->
	
	<pays nom="France">
	
		<agence ville="Nantes">
			<responsable>
				<nom>Hautine</nom>
				<prenom>Guy</prenom>
			</responsable>
		</agence>

		<agence ville="Clermont-Ferrand">
			<responsable>
				<nom>Assin</nom>
				<prenom>Marc</prenom>
			</responsable>
		</agence>

	</pays>
	
	
	<!-- - - - - - - - -->
	<!--   Belgique    -->
	<!-- - - - - - - - -->
	
	<pays nom="Belgique">
	
		<agence ville="Bruxelles">

			<responsable>
				<nom>Menvussa</nom>
				<prenom>Gérard</prenom>
			</responsable>
			
		</agence>
		
	</pays>

</kubenbois>
