=== Tirtan/semestre3/web/xml/partie3/stock-03.dtd
<!ELEMENT stock (editeur+, personne+, jeu+)>
	<!ELEMENT editeur (#PCDATA)>
	<!ATTLIST editeur id ID #REQUIRED>

	<!ELEMENT personne (prenom?, nom, dte_naiss?, nationalite)>
	<!ATTLIST personne id ID #REQUIRED>
		<!ELEMENT prenom (#PCDATA)>
		<!ELEMENT nom (#PCDATA)>
		<!ELEMENT dte_naiss (#PCDATA)>
		<!ELEMENT nationalite (#PCDATA)>

	<!ELEMENT jeu (titre, annee, nb_joueur, age, duree, edite_par+, cree_par+)>
	<!ATTLIST jeu couv CDATA #REQUIRED>
		<!ELEMENT titre (#PCDATA)>
		<!ELEMENT annee (#PCDATA)>
		<!ELEMENT nb_joueur EMPTY>
			<!ATTLIST nb_joueur mini CDATA #REQUIRED
								maxi CDATA #REQUIRED>

		<!ELEMENT age EMPTY>
			<!ATTLIST age mini CDATA #REQUIRED>
		<!ELEMENT duree EMPTY>
			<!ATTLIST duree minute CDATA #REQUIRED>
		<!ELEMENT edite_par EMPTY>
			<!ATTLIST edite_par lien_editeur IDREF #REQUIRED>
		<!ELEMENT cree_par EMPTY>
		<!ATTLIST cree_par lien_personne IDREF #REQUIRED
						   role (auteur | illustrateur) #REQUIRED>

=== Tirtan/semestre3/web/xml/partie3/stock-03.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!DOCTYPE stock SYSTEM "stock-03.dtd" >

<?xml-stylesheet type="text/xsl" href="25-3-stock-css.xsl"?>

<stock>

	<!-- - - - - - - - - - - -->
	<!-- Liste des Editeurs  -->
	<!-- - - - - - - - - - - -->
	
	<editeur id="e001">Asmodée            </editeur>
	<editeur id="e002">Bombyx             </editeur>
	<editeur id="e003">Days of Wonder     </editeur>
	<editeur id="e004">Edge               </editeur>
	<editeur id="e005">Filosofia          </editeur>
	<editeur id="e006">Funforge           </editeur>
	<editeur id="e007">Gigamic            </editeur>
	<editeur id="e008">Hurrican           </editeur>
	<editeur id="e009">Iello              </editeur>
	<editeur id="e010">Intrafin           </editeur>
	<editeur id="e011">Jeux Descartes     </editeur>
	<editeur id="e012">Ludodélire         </editeur>
	<editeur id="e013">Matagot            </editeur>
	<editeur id="e014">Repro production   </editeur>
	<editeur id="e015">Ystari             </editeur>
	<editeur id="e016">Blue Orange        </editeur>
	<editeur id="e017">Huch &#38; Friends </editeur>
	<editeur id="e018">Feurland Spiele    </editeur>
	<editeur id="e019">Z-Man Games        </editeur>
	<editeur id="e020">Lui-Même           </editeur>
	<editeur id="e021">Stronghold games   </editeur>
	<editeur id="e022">Pegasus Spiele     </editeur>
	<editeur id="e023">EggertSpiele       </editeur>
	
	<!-- - - - - - - - - - - -->
	<!-- Liste des personnes -->
	<!-- - - - - - - - - - - -->
	<personne id="p0001"><prenom>Uwe            </prenom> <nom>Rosenberg      </nom> <dte_naiss>27/03/1970</dte_naiss> <nationalite>Allemagne      </nationalite>   </personne>
	<personne id="p0002"><prenom>Antoine        </prenom> <nom>Bauza          </nom> <dte_naiss>25/08/1978</dte_naiss> <nationalite>France         </nationalite>   </personne> 
	<personne id="p0003"><prenom>Alan           </prenom> <nom>R. Moon        </nom> <dte_naiss>18/11/1951</dte_naiss> <nationalite>Angleterre     </nationalite>   </personne>
	<personne id="p0004"><prenom>Philippe       </prenom> <nom>Keyaerts       </nom>                                   <nationalite>Belgique       </nationalite>   </personne>
	<personne id="p0005"><prenom>Bruno          </prenom> <nom>Faidutti       </nom> <dte_naiss>23/10/1961</dte_naiss> <nationalite>France         </nationalite>   </personne>
	<personne id="p0006"><prenom>Bruno          </prenom> <nom>Cathala        </nom> <dte_naiss>22/11/1963</dte_naiss> <nationalite>France         </nationalite>   </personne>
	<personne id="p0007"><prenom>Alexander      </prenom> <nom>Pfister        </nom> <dte_naiss>18/10/1971</dte_naiss> <nationalite>Autriche       </nationalite>   </personne>
	<personne id="p0008"><prenom>Inka           </prenom> <nom>Brand          </nom> <dte_naiss>19/03/1977</dte_naiss> <nationalite>Allemagne      </nationalite>   </personne>
	<personne id="p0009"><prenom>Markus         </prenom> <nom>Brand          </nom> <dte_naiss>01/10/1975</dte_naiss> <nationalite>Allemagne      </nationalite>   </personne>
	<personne id="p0010"><prenom>Dominique      </prenom> <nom>Ehrhard        </nom> <dte_naiss>05/03/1958</dte_naiss> <nationalite>France         </nationalite>   </personne>
	<personne id="p0011"><prenom>Reiner         </prenom> <nom>Knizia         </nom> <dte_naiss>16/11/1957</dte_naiss> <nationalite>Allemage       </nationalite>   </personne>
	<personne id="p0012"><prenom>Dennis         </prenom> <nom>Lohausen       </nom>                                   <nationalite>Allemagne      </nationalite>   </personne>
	<personne id="p0013"><prenom>Klemens        </prenom> <nom>Franz          </nom> <dte_naiss>17/04/1979</dte_naiss> <nationalite>Autriche       </nationalite>   </personne>
	<personne id="p0014"><prenom>Arnaud         </prenom> <nom>Demaegd        </nom>                                   <nationalite>France         </nationalite>   </personne>  
	<personne id="p0015"><prenom>Cyril          </prenom> <nom>Demaegd        </nom>                                   <nationalite>France         </nationalite>   </personne>  
	<personne id="p0016"><prenom>Michel         </prenom> <nom>Lalet          </nom> <dte_naiss>29/01/1953</dte_naiss> <nationalite>France         </nationalite>   </personne>  
	<personne id="p0017"><prenom>Andreas        </prenom> <nom>Pelikan        </nom>                                   <nationalite>Autriche       </nationalite>   </personne>  
	<personne id="p0018"><prenom>Andreas        </prenom> <nom>Resch          </nom>                                   <nationalite>Autriche       </nationalite>   </personne>  
	<personne id="p0019"><prenom>Charles        </prenom> <nom>Chevalier      </nom> <dte_naiss>04/11/1966</dte_naiss> <nationalite>France         </nationalite>   </personne>  
	<personne id="p0020"><prenom>Jade           </prenom> <nom>Mosch          </nom>                                   <nationalite>France         </nationalite>   </personne>  
	<personne id="p0021"><prenom>Ludovic        </prenom> <nom>Maublanc       </nom> <dte_naiss>xx/xx/1975</dte_naiss> <nationalite>France         </nationalite>   </personne>
	<personne id="p0022"><prenom>Julien         </prenom> <nom>Delval         </nom> <dte_naiss>xx/xx/1972</dte_naiss> <nationalite>France         </nationalite>   </personne>
	<personne id="p0023"><prenom>Piérô          </prenom> <nom>La Lune        </nom>                                   <nationalite>France         </nationalite>   </personne>
	<personne id="p0024"><prenom>Xavier         </prenom> <nom>Colette        </nom>                                   <nationalite>Belgique       </nationalite>   </personne>	
	<personne id="p0025"><prenom>Cyril          </prenom> <nom>Bouquet        </nom>                                   <nationalite>France         </nationalite>   </personne>
	<personne id="p0026"><prenom>Clément        </prenom> <nom>Masson         </nom>                                   <nationalite>France         </nationalite>   </personne>	
   <personne id="p0027"><prenom>Cérard         </prenom> <nom>Mathieu        </nom> <dte_naiss>xx/xx/1949</dte_naiss> <nationalite>France         </nationalite>   </personne>		
   <personne id="p0028"><prenom>Jeremy         </prenom> <nom>Masson         </nom>                                   <nationalite>France         </nationalite>   </personne>
   <personne id="p0029"><prenom>Florence       </prenom> <nom>Magnin         </nom> <dte_naiss>07/03/1950</dte_naiss> <nationalite>France         </nationalite>   </personne>
   <personne id="p0030"><prenom>Jean-Louis     </prenom> <nom>Mourier        </nom> <dte_naiss>06/11/1962</dte_naiss> <nationalite>France         </nationalite>   </personne>
   <personne id="p0031"><prenom>Didier         </prenom> <nom>Graffet        </nom> <dte_naiss>09/04/1970</dte_naiss> <nationalite>France         </nationalite>   </personne>
   <personne id="p0032"><prenom>Cyril          </prenom> <nom>Saint Blancat  </nom>                                   <nationalite>France         </nationalite>   </personne>
   <personne id="p0033"><prenom>Miguel         </prenom> <nom>Coimbra        </nom> <dte_naiss>09/12/1977</dte_naiss> <nationalite>France         </nationalite>   </personne>
   <personne id="p0034"><prenom>Joêl           </prenom> <nom>Picksel        </nom>                                   <nationalite>France         </nationalite>   </personne>
   <personne id="p0035"><prenom>Nicolas        </prenom> <nom>Fructus        </nom> <dte_naiss>24/06/1970</dte_naiss> <nationalite>France         </nationalite>   </personne>
   <personne id="p0036">                                 <nom>Yuio           </nom>                                   <nationalite>Belgique       </nationalite>   </personne>
   <personne id="p0037"><prenom>Marie          </prenom> <nom>Cardouat       </nom>                                   <nationalite>France         </nationalite>   </personne>  
	

	
	<!-- - - - - - - - - - - -->
	<!-- Liste des jeux      -->
	<!-- - - - - - - - - - - -->
		<jeu couv="route_du_verre">
			<titre>La route du verre     </titre>
			<annee>2013                  </annee>
			
			<nb_joueur mini="1" maxi="4"/>
			<age       mini="12"        />
			<duree     minute="60"      />
			
			<edite_par lien_editeur="e005" />
			<edite_par lien_editeur="e018" />
			<edite_par lien_editeur="e019" />
			
			<cree_par lien_personne="p0001" role="auteur"       />
			<cree_par lien_personne="p0012" role="illustrateur" />
			
		</jeu>

		<jeu couv="agricola">
			<titre>Agricola              </titre>
			<annee>2008                  </annee>
			
			<nb_joueur mini="1" maxi="5" />
			<age       mini="12"         />
			<duree     minute="120"      />
			
			<edite_par lien_editeur="e015" />

			<cree_par lien_personne="p0001" role="auteur"       />
			<cree_par lien_personne="p0013" role="illustrateur" />			
		</jeu>


		<jeu couv="patchwork">
			<titre>Patchwork              </titre>
			<annee>2015                   </annee>
			
			<nb_joueur mini="2" maxi="2" />
			<age       mini="7"          />
			<duree     minute="30"       />
			
			<edite_par lien_editeur="e006" />
			
			<cree_par lien_personne="p0001" role="auteur"         />
			<cree_par lien_personne="p0013" role="illustrateur"   />
		</jeu>
	
		<jeu couv="le_havre">
			<titre>Le Havre               </titre>
			<annee>2009                   </annee>

			<nb_joueur mini="1" maxi="5" />
			<age       mini="12"         />
			<duree     minute="180"      />
			
			<edite_par lien_editeur="e015" />
			
			<cree_par lien_personne="p0001" role="auteur"         />
			<cree_par lien_personne="p0013" role="illustrateur"   />
			
		</jeu>
		
		<jeu couv="portes_loyang">
			<titre>Aux portes de Loyang   </titre>
			<annee>2010                   </annee>

			<nb_joueur mini="1" maxi="4" />
			<age       mini="10"         />
			<duree     minute="120"      />
			
			<edite_par lien_editeur="e010" />
			
			<cree_par lien_personne="p0001" role="auteur"         />
